### ISSUE TITLE
Fix front page

### ISSUE THREAD

**Issue by rufuspollock** [okfn/handbook#84]
- [x] Get involved should go
- [x] "Data Guide" as new name for patterns section
- [x] "Labs Guide" - how to get involved, how things work, contributor instructions

**Comment by gsilvapt** [comment]
https://github.com/okfn/handbook/issues/87 complements this issue

**Comment by rufuspollock** [comment]
@gsilvapt i am not sure #87 completes this issue - did you mean "comple_ments_?

**Comment by gsilvapt** [comment]
Yes, totally. It was late already :laughing:

**Comment by gsilvapt** [comment]
@rgrp, as we disscused in the now closed issue #95, here follows a few suggestions to work on the homepage:
- [ ] Add a small paragraph before the three "menus" pointing out to different guides 
- [ ] In the menu, regardless of how we structure this, we should have an entire table of contents of the guides there so that users can easily click and go back whenever they want.
- [ ] In addition, it would be great to add something so that users can move on the next part of the tutorial when reading it. Or go back if they miss something.

I haven't done any of these because I don't know how. When writing the paragraph, the thing just looks out of place and as if the texts was aligned to the left. I tried `p class = "container-fluid"` and `p class = "container"` but the outcome is the same. You guys have wrote a lot of stuff in the CSS files, so maybe there is an easy way to do it.

As for the menu suggestions, I have no idea where the menu is stored, how to generate Table of Contents (ToC, if that is even possible) and how to work on a simple way to allow users to go back and forth in the guide.

Anyone can guide me and/or show me some documentation so that I can make that happen?

**Comment by rufuspollock** [comment]
@gsilvapt not totally clear what you mean. Great if we can sync briefly.

**Comment by gsilvapt** [comment]
@rgrp: I am having issues connecting to the Wi-Fi network. Perhaps we can do this during the afternoon, if you are around.

But still, are you referring to my last paragraph or anything in particular in my previous comment?

**Comment by gsilvapt** [comment]
@rgrp I think we can also close this issue. These items have been solved, I think.

**Comment by rufuspollock** [comment]
FIXED.
